/**
 * Compiler Error Codes
 * Standardized error codes for compiler service responses
 */

export enum CompilerErrorCode {
	// Compilation errors
	COMPILATION_ERROR = 'COMPILATION_ERROR',
	SYNTAX_ERROR = 'SYNTAX_ERROR',
	DECLARATION_ERROR = 'DECLARATION_ERROR',
	TYPE_MISMATCH_ERROR = 'TYPE_MISMATCH_ERROR',
	SCOPE_VIOLATION = 'SCOPE_VIOLATION',

	// Runtime errors
	RUNTIME_ERROR = 'RUNTIME_ERROR',
	SEGMENTATION_FAULT = 'SEGMENTATION_FAULT',
	FLOATING_POINT_EXCEPTION = 'FLOATING_POINT_EXCEPTION',
	MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED',

	// Timeout errors
	TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED',
	COMPILATION_TIMEOUT = 'COMPILATION_TIMEOUT',

	// System errors
	SERVER_BUSY = 'SERVER_BUSY',
	CONTAINER_ERROR = 'CONTAINER_ERROR',
	INTERNAL_ERROR = 'INTERNAL_ERROR',

	// Validation errors
	INVALID_CODE = 'INVALID_CODE',
	CODE_TOO_LARGE = 'CODE_TOO_LARGE',
	DANGEROUS_CODE = 'DANGEROUS_CODE',
	RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
}

export interface CompilerError {
	code: CompilerErrorCode
	message: string
	details?: string
	lineNumber?: number
	columnNumber?: number
}
